MYSHOPEE/urls.py
from django.contrib import admin
from django.urls import path,include
import base
from base import views
import chatbot

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',include('base.urls')),
    path('chatbot/',include('chatbot.urls')),
    path('',views.home,name='home'),
]

base/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from chatbot.views import home as chatHome
app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('product/<str:pk>/',views.ProductView,name='product'),
    path('Update-Product/<str:pk>/',views.updateProduct,name="update-product"),
    path('delete-Product/<str:pk>/',views.deleteProduct,name="delete-product"),
    path('Add-Product/',views.addProduct,name="add-product"),
    path('search-product/',views.SearchedProduct.as_view(),name="search-product"),
    path('navbar/', views.navbar, name='navbar'),
    path('login-page/',views.LoginPage.as_view(),name="login"),
    path('logout-page/',views.logoutUser.as_view(),name="logout"),
    path('register/',views.registerPage.as_view(),name="register"),
    path('cart/',views.CartView.as_view(),name="cart-product"),
    path('AddtoCart/<str:pk>/',views.AddtoCart.as_view(),name='add-cart'),
    path('contact/',chatHome,name="contact-user"),
]

chatbot/urls.py
from django.urls import path,include
from . import views
app_name = 'chatbot'

urlpatterns = [
    path('',views.home,name="home"),
    path('Display-user/',views.displayUser,name="display-user"),
    path('connect/<str:pk>',views.sendUserChatRequest,name="connect-user"),
    path('chat/',views.getRoom,name="room"),
]

chatbot/models.py
from django.db import models

class chatRequest(models.Model):
    request = models.CharField(max_length=100)
    def __str__(self):
        return self.request


class chatbotUser(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=12)
    created = models.DateField(auto_now=True)
    updated = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
# Create your models here.

chatbot/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from chatbot.user_services import getUsers,saveUser,toggle_online,cacheDataBackend
import threading
from django.core.cache import cache
import json
import string
import random
from base.views import login

# Create your views here.

def home(request):
    toggle_online(request,'online')
    room_name = None
    connect_request_user = None 
    if request.user.is_authenticated:
        cache_obj = cacheDataBackend()
        cache_data = cache_obj.getter(request.user.id)
        if cache_data:
            room_name = cache_data['room_name']
            connect_request_userid=cache_data['connect_request_userid']
            connect_request_user = User.objects.get(id=connect_request_userid)
    context={'room_name':room_name,'connect_request_user':connect_request_user}
    return render(request,'chatbot/home.html',context)



@login_required(login_url='login')
def sendUserChatRequest(request,pk):
    passed_user = User.objects.get(id=pk)
    room_name=''.join(random.choices(string.ascii_uppercase +string.digits, k=9)) # 9 length room_name
    data = {
    'connect_receiver_userid': str(pk),
    'connect_request_userid': str(request.user.id),
    'room_name':room_name
    }
    cache_obj = cacheDataBackend()
    cache_obj.setter(pk,data)
     
    context={'passed_user':passed_user,'room_name': room_name}
    return render(request,'chatbot/chatroom.html',context)


@login_required(login_url='login')
def getRoom(request):
    cache_obj = cacheDataBackend()
    cache_data = cache_obj.getter(request.user.id)
    passed_user=None
    room_name = None
    if cache_data:
        connect_request_userid=cache_data['connect_request_userid']
        passed_user = User.objects.get(id=connect_request_userid)
        room_name = cache_data['room_name']

    cache_obj.delete(request.user.id)
    context={'passed_user':passed_user,'room_name': room_name}
    return render(request, 'chatbot/chatroom.html', context)



@login_required(login_url='login')
def displayUser(request):
    users = User.objects.all()
    context = {'users':users}
    return render(request,'chatbot/Interest.html',context)

chatbot/templates/chatbot/Interest.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div>
    {%if users.count > 0  %}
    {% if Interest != None %}
    <h4>Topic : {{Interest}}</h4>
    <h6>Available User :  {{users.count}}</h6>
    {% endif %}
    {% for user in users %}
    <div>
        <a href="#">
        {% if request.is_authenticated  %}
        <img class="indicator" src="{% static 'images/online.PNG' %}" />
        {% else %}
        <img class="indicator" src="{% static 'images/offline.PNG' %}" />
        {% endif %}
        {{user.username}}
        </a>
        <br>
        <a href="{% url 'chatbot:connect-user' user.id %}">Connect</a>
    </div>
    <hr>
    {% endfor %}
    {% else %}
    <h3>No user is online except you </h3>
    <a href="{{request.META.HTTP_REFERER}}">GO BACK</a>
    {% endif %}
    
</div>

{% endblock %}

chatbot/templates/chatbot/chatroom.html
{% extends 'main.html' %}
{% block content %}
<h4>User    :{{passed_user.username}}</h4>
<h4>Email   :{{passed_user.email}}</h4>
<h4>gender  :{{passed_user.gender}}</h4>
<h4>Country :{{passed_user.country}}</h4>
    <textarea id="chat-log" cols="100" rows="10"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <a href="{{request.META.HTTP_REFERER}}">GO BACK</a>
    
    
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock %}

chatbot/templates/chatbot/home.html
{% extends 'main.html' %}

{% block content %}
<h1>Contact</h1>
{% if request.user.is_authenticated %}
<a href="{% url 'chatbot:display-user' %}">Support user</a>
<br>
{% if room_name != None  and connect_request_user != None %}
<label>Connection Request from : {{connect_request_user.username}}  </label>
<a href="{% url 'chatbot:room' %}">Connect</a>

{% endif %}
{% else %}
<p>Login required </p>
{% endif %}
{% endblock %}