MYSHOPEE/urls.py
from django.contrib import admin
from django.urls import path,include
import base
from base import views
import chatbot

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',include('base.urls')),
    path('chatbot/',include('chatbot.urls')),
    path('',views.home,name='home'),
]

base/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from chatbot.views import home as chatHome
app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('product/<str:pk>/',views.ProductView,name='product'),
    path('Update-Product/<str:pk>/',views.updateProduct,name="update-product"),
    path('delete-Product/<str:pk>/',views.deleteProduct,name="delete-product"),
    path('Add-Product/',views.addProduct,name="add-product"),
    path('search-product/',views.SearchedProduct.as_view(),name="search-product"),
    path('navbar/', views.navbar, name='navbar'),
    path('login-page/',views.LoginPage.as_view(),name="login"),
    path('logout-page/',views.logoutUser.as_view(),name="logout"),
    path('register/',views.registerPage.as_view(),name="register"),
    path('cart/',views.CartView.as_view(),name="cart-product"),
    path('AddtoCart/<str:pk>/',views.AddtoCart.as_view(),name='add-cart'),
    path('contact/',chatHome,name="contact-user"),
]

templates/footer.html
<div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
    </footer>
  </div>

templates/main.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>MYSHOPEE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel = "stylesheet" href="{% static 'styles/styles.css' %}"/>
  </head>
  <body>
    {%include 'navbar.html' %}
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% block content %}

    {% endblock %}
    
    
    {% include 'footer.html'%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script
      <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">MYSHOPEE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:contact-user' %}">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'base:navbar' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <!--<li><a class="dropdown-item" href="#">Electronics</a></li>
              <li><a class="dropdown-item" href="#">Fashion</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Mobile</a></li>
              <li><a class="dropdown-item" href="#">Appliances</a></li> -->
              {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'base:search-product'%}?q={{category.name}}">{{ category.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
        <div>
            <form class="d-flex" role="search" method="GET" action="{% url 'base:search-product' %}">
                <input class="form-control me-2" type="search" placeholder="MYSHOPEE.." aria-label="Search" name="q">
                
              </form>
        </div>
        <div class="login_cart">
        {% if request.user.is_authenticated %}
        <div class="login_bar">
          <a href="{% url 'base:logout' %}">
              <img src="{% static 'images/avatar.svg' %}" />
              <p>@{{user.username}}</p>  
            </a>
      </div>
        {% else %}   
        <div class="login_bar">
            <a href="{% url 'base:login' %}">
                <img src="{% static 'images/avatar.svg' %}" />
                <p>Login</p>
              </a>
        </div>
        {% endif %}   
        <div class="cart">
            <a class="cart_link" href="{% url 'base:cart-product' %}"><img src="{% static 'images/cart_img.jpg' %}"/><span>Cart</span></a> 
        </div>
    </div>
      </div>
    </div>
  </nav>