MYSHOPEE/urls.py
from django.contrib import admin
from django.urls import path,include
import base
from base import views
import chatbot

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',include('base.urls')),
    path('chatbot/',include('chatbot.urls')),
    path('',views.home,name='home'),
]

base/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from chatbot.views import home as chatHome
app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('product/<str:pk>/',views.ProductView,name='product'),
    path('Update-Product/<str:pk>/',views.updateProduct,name="update-product"),
    path('delete-Product/<str:pk>/',views.deleteProduct,name="delete-product"),
    path('Add-Product/',views.addProduct,name="add-product"),
    path('search-product/',views.SearchedProduct.as_view(),name="search-product"),
    path('navbar/', views.navbar, name='navbar'),
    path('login-page/',views.LoginPage.as_view(),name="login"),
    path('logout-page/',views.logoutUser.as_view(),name="logout"),
    path('register/',views.registerPage.as_view(),name="register"),
    path('cart/',views.CartView.as_view(),name="cart-product"),
    path('AddtoCart/<str:pk>/',views.AddtoCart.as_view(),name='add-cart'),
    path('contact/',chatHome,name="contact-user"),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=150,blank=False)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    #quantity
    #image_url
    category = models.ForeignKey(Category,on_delete=models.CASCADE,blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name[:20]
    
    class Meta:
        ordering = ['-updated','-created']


class cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    #quantity = models.IntegerField(blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name
    
    class Meta:
        ordering = ['updated','created']

base/forms.py
from .models import Product
from django.forms import ModelForm

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

base/views.py
from django.shortcuts import render,redirect
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .models import Product,Category,User,cart
from .forms import ProductForm
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from rest_framework.throttling import UserRateThrottle,AnonRateThrottle
from rest_framework.views import APIView
from rest_framework.decorators import api_view,throttle_classes,action,APIView
from .serializers import CategorySerializer
import chatbot

# Create your views here.

def home(request):
    products = Product.objects.all()
    category = Category.objects.all()
    carts = cart.objects.all()
 #   if request.user.is_authenticated:
  #      carts = request.user.cart_set.all()
    context={'products':products,'category':category,'carts':carts}
    return render(request,'base/home.html',context)

def ProductView(request,pk):
    product = Product.objects.get(id=pk)
    context={'product':product}
    response =  render(request,'base/Product.html',context)
    return response

@login_required(login_url='login')
def updateProduct(request,pk):
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    if request.method=='POST':
        form = ProductForm(request.POST,instance=product)
        if form.is_valid():
            form.save()
            return redirect('home')
    context={'form':form}
    return render(request,'base/create_update_product.html',context)

@login_required(login_url='login')
def deleteProduct(request,pk):
    product = Product.objects.get(id=pk)
    if request.method=='POST':
        product.delete()
        return redirect('home')
    context = {'obj':product}
    return render(request,'base/delete_product.html',context)

@login_required(login_url='login')
def addProduct(request):
    form = ProductForm()
    if request.method=='POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    context={'form':form}
    return render(request,'base/create_update_product.html',context)

def navbar(request):
        categories = Category.objects.all()
        return {
            'categories': categories,
            'chatbot':chatbot,
        }


#---------------------------------->Class based views <--------------------------------------

class registerPage(APIView):
    def post(self,request):
        page='register'
        form = UserCreationForm()
        if request.method=='POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.username = user.username
                user.save()
                login(request,user)
                return redirect('home')
            else:
                messages.error(request,"An error occurred during registration")
                return self.get(request)

    def get(self,request):
        page='register'
        form = UserCreationForm()
        context = {'page':page,'form':form}
        return render(request,'base/login_register.html',context)
    

class AddtoCart(APIView):
    @method_decorator(login_required(login_url='login'))
    def get(self,request,pk):
        user = request.user
        product = Product.objects.get(id=pk)
        chk = cart.objects.filter(user = user , product=product)
        if chk.count()==0:
            cartProduct = cart.objects.create(
                user = user,
                product=product
            )
        return redirect('base:cart-product')
    
class logoutUser(APIView):
    @method_decorator(login_required(login_url='login'))
    def get(self,request):
        logout(request)
        request.session.flush()
        response = redirect('home')
        response.delete_cookie('csrftoken')
        return response

class LoginPage(APIView):
    throttle_classes = [AnonRateThrottle]
    def post(self,request):
        page='login'
        if request.user.is_authenticated:
            return redirect('home')
        if request.method=='POST':
            #print(request.COOKIES.get('csrftoken'))
            username = request.POST.get('username')
            password = request.POST.get('password')
            try:
                user = User.objects.get(username=username)
                user = authenticate(request,username=username,password=password)
                if user is not None:
                    login(request,user)
                    return redirect('home')
                else:
                    messages.error(request,'Username or password does not exists')
                    return self.get(request)
            except:
                messages.error(request,'User does not exists')
                return self.get(request)
            
    def get(self,request):
        page='login'
        context={'page':page}
        return render(request,'base/login_register.html',context)
    
class SearchedProduct(APIView):
    category = Category.objects.all()
    throttle_classes=[AnonRateThrottle,UserRateThrottle]
    def get(self,request):
        q = request.GET.get('q') if request.GET.get('q') != None else ''
        filter_products = self.get_queryset(Product,q)        
        search_param = q
        #serialized = CategorySerializer(self.category,many=True)
        #print(serialized.data)
        paginator = Paginator(filter_products, 10)   #10 search item on single page
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
        context={'filter_products':filter_products,'category':self.category,'page': page,'search_param':search_param}
        response= render(request,'base/filtered_product.html',context)
        #response.set_cookie('key1',['val1','val2'])
        #response.delete_cookie('key1')
        return response
    
    def get_queryset(self,Product,key):
        filter_products = Product.objects.filter(
            Q(name__icontains=key) |
            Q(description__icontains=key) |
            Q(category__name__icontains=key)
        )
        return filter_products
    
class CartView(APIView):
    @method_decorator(login_required(login_url='login'))
    def get(self,request):
        cartItem = request.user.cart_set.all()
        sum_of_cart_amount = 0
        for item in cartItem:
            sum_of_cart_amount = sum_of_cart_amount + item.product.price
        context={'cartItem':cartItem,'sum_of_cart_amount':sum_of_cart_amount}
        return render(request,'base/ProductCart.html',context)

base/templates/base/Product.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<h3>{{product.name}}</h3>
<h3>{{product.price}}</h3>
<h5>{{product.description}}</h5>
<h6>{{product.Category.name}}</h6>
<a href="{% url 'base:update-product' product.id %}"><span>Edit</span></a>
<a href="{% url 'base:delete-product' product.id %}"><span>Delete</span></a>
<a href="{% url 'base:add-cart' product.id %}" class="btns">Add to Cart</a>

{% endblock %}

base/templates/base/ProductCart.html
{% extends 'main.html' %}
{% block content %}
<style>
    .cart-class{
        display:grid;
        grid-template-columns: 3fr 2fr;
    }
    .filter_product{
        display:grid;
        grid-template-columns: 1fr 2fr;
        vertical-align: top;
        text-align: center;
        margin: 10px;
        padding: 10px;
        border: 1px solid #ccc
    }
    .main_filter_container{
        display:grid;
        grid-template-columns: 1fr 4fr;
    }
    .filter_product img{
        width: 200px;
        height: 200px;
        margin-bottom: 10px;
    }
</style>
<p><center><b>Total Cart item : {{cartItem.count}}</b></center></p>
<div class="cart-class">
    <div>
    {% for cart in cartItem %}
    <div>
        <a href="{% url 'base:product' cart.product.id %}" title="{{cart.product.name}}">
            <div class="filter_product">
                <div>
                    <img src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg" alt="{{cart.product.name}} image"/>
                </div>
                <div>
                    
                    <p>{{cart.product.name}} </p>
                    <span>{{cart.product.price}}</span>
                    <p><small>{{cart.product.category}}</small></p>
                </div>
            </div>
            </a>
    </div>
    {% endfor %}
</div>
<div>
    <h4>Total Amount</h4>
    <hr>
    <p><b>Payable Amount :</b> ${{sum_of_cart_amount}} </p>
</div>
</div>

{% endblock %}

base/templates/base/Recent_section.html
<style>
    .scroll-container {
  position: relative;
  overflow: hidden;
}

.scroll-content {
  display: flex;
  flex-wrap: nowrap;
  overflow-x: auto;
  scroll-behavior: smooth;
  scroll-snap-type: x mandatory;
}

.scroll-button {
  overflow-x: hidden;
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 40px;
  height: 40px;
  font-size: 20px;
  background: #f1f1f1;
  border: none;
  cursor: pointer;
  display:None
}

.scroll-button.left {
  left: 10px;
}

.scroll-button.right {
  right: 10px;
}

.no-bullets {
    list-style: none;
  }

</style>
<section class="products">
    <a href="{% url 'base:add-product' %}"><h2>Add product </h2></a>
    <h2>Featured Products</h2>
    <div class="scroll-container">
      <div class="scroll-content">
          {% for product in products %}
              <ul class="no-bullets">
                  <li>
                      <div class="product-item">
                      <a href="{% url 'base:product' product.id %}" title="{{product.name}}">
                      <img src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg" alt="Product 1">
                      <h3>{{product}}</h3>
                      <p>${{product.price}}</p>
                      </a>
                      <a href="{% url 'base:add-cart' product.id %}" class="btn">Add to Cart</a>
                      <!--<a href="#" class="btn">Go to Cart</a>-->
                      </div>
                  </li>
              </ul>
          {% endfor %}
      </div>
  <!--<button class="scroll-button left">&lt;</button>
  <button class="scroll-button right">&gt;</button>-->
  </div>

  
    
    <div>
        <b><h2>Category</h2></b>
        {% for cat in category %}
        {% if cat.product_set.all.count > 0 %}
        <h5>{{cat.name}} - {{cat.product_set.all.count}} Products</h5>
        <div class="scroll-container">
            <div class="scroll-content">
                {% for product in cat.product_set.all %}
                    <ul class="no-bullets">
                        <li>
                            <div class="product-item">
                            <a href="{% url 'base:product' product.id %}" title="{{product.name}}">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg" alt="Product 1">
                            <h3>{{product}}</h3>
                            <p>${{product.price}}</p>
                            </a>
                            <a href="{% url 'base:add-cart' product.id %}" class="btn">Add to Cart</a>
                            <!--<a href="#" class="btn">Go to Cart</a>-->
                            </div>
                        </li>
                    </ul>
                
                {% endfor %}
            </div>
        <!--<button class="scroll-button left">&lt;</button>
        <button class="scroll-button right">&gt;</button> -->
        </div>
        {% endif %}
        {% endfor %}
    </div>
    
    <script>
      
var scrollContainer = document.querySelector(".scroll-container");
var scrollContent = document.querySelector(".scroll-content");
var scrollButtons = document.querySelectorAll(".scroll-button");

function toggleScrollButtons() {
  var contentWidth = scrollContent.scrollWidth;
  var containerWidth = scrollContainer.clientWidth;

  if (contentWidth > containerWidth) {
    // Display the buttons if content exceeds the container size
    scrollButtons.forEach(function(button) {
      button.style.display = "inline";
    });
  } else {
    // Hide the buttons if content fits within the container
    scrollButtons.forEach(function(button) {
      button.style.display = "none";
    });
  }
}

// Call the function on window load and resize events
window.addEventListener("load", toggleScrollButtons);
window.addEventListener("resize", toggleScrollButtons);
</script>

<script>
  document.querySelector(".scroll-button.left").addEventListener("click", function () {
document.querySelector(".scroll-content").scrollBy({
left: -200,
behavior: "smooth"
});
});

document.querySelector(".scroll-button.right").addEventListener("click", function () {
document.querySelector(".scroll-content").scrollBy({
left: 200,
behavior: "smooth"
});
});


</script>
</section>

<!--
     {% for cat in category %}
        <div><p>{{cat.id}}---{{cat.name}}-!-!-{{cat.products_set.all.count}}</p></div>
        {% if cat.products_set.all.count > 0 %}
        {% for product in cat.products_set.all %}
        <li>{{ product.name }}</li>
        {% endfor %}
        {% endif %}
        {% endfor %}

        <script>
       document.querySelector(".scroll-button.left").addEventListener("click", function () {
  document.querySelector(".scroll-content").scrollBy({
    left: -200,
    behavior: "smooth"
  });
});

document.querySelector(".scroll-button.right").addEventListener("click", function () {
  document.querySelector(".scroll-content").scrollBy({
    left: 200,
    behavior: "smooth"
  });
});


    </script>
-->

base/templates/base/create_update_product.html
{% extends 'main.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>
{% endblock %}

base/templates/base/delete_product.html
{% extends 'main.html' %}
{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you Sure you want to delete {{obj}}?</p>
    <a href="{{request.META.HTTP_REFERER}}">GO BACK</a>
    <input type="submit" value="Confirm"/>
</form>
{% endblock %}

base/templates/base/filtered_product.html
{% extends 'main.html' %}
{% block content %}
<style>
    .filter_product{
        display:grid;
        grid-template-columns: 1fr 2fr;
        vertical-align: top;
        text-align: center;
        margin: 10px;
        padding: 10px;
        border: 1px solid #ccc
    }
    .main_filter_container{
        display:grid;
        grid-template-columns: 1fr 4fr;
    }
    .filter_product img{
        width: 200px;
        height: 200px;
        margin-bottom: 10px;
    }
    .page_button{
        
        font: bold 15px Arial;
        text-decoration: none;
        background-color: #EEEEEE;
        color: #333333;
        padding: 2px 6px 2px 6px;
        border-top: 1px solid #CCCCCC;
        border-right: 1px solid #333333;
        border-bottom: 1px solid #333333;
        border-left: 1px solid #CCCCCC;
    }
</style>
<div class="main_filter_container">
    <div>
        {% include 'base/filters.html' %}
    </div>
    <div>
        <h3>{{filter_products.count }} Products Available </h3>
        <hr>
        {%for product in page %}
        <a href="{% url 'base:product' product.id %}" title="{{product.name}}">
        <div class="filter_product">
            <div>
                <img src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg" alt="{{product.name}} image"/>
            </div>
            <div>
                
                <p>{{product.name}} </p>
                <span>{{product.price}}</span>
                <p><small>{{product.category}}</small></p>
            </div>
        </div>
        </a>
        <hr>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                <span class="current-page">{{ page.number }}</span>
                {% if page.has_previous %}
                    <a class="page_button" href="?q={{search_param}}&page=1">&laquo; first</a>
                    <a class="page_button" href="?q={{search_param}}&page={{ page.previous_page_number }}">previous</a>
                {% endif %}
        
                
        
                {% if page.has_next %}
                    <a class="page_button" href="?q={{search_param}}&page={{ page.next_page_number }}">next</a>
                    <a class="page_button" href="?q={{search_param}}&page={{ page.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div> 

{% endblock %}



<!--
     <div>
        <h3>{{filter_product_count}} Products Available</h3>
        <hr>
        <section class="products">
        {%for product in filter_products %}
       
            <ul class="no-bullets">
                <li>
                    <div class="product-item">
                    <a href="{% url 'product' product.id %}" title="{{product.name}}">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg" alt="Product 1">
                    <h3>{{product}}</h3>
                    <p>${{product.price}}</p>
                    </a>
                    <a href="#" class="btn">Add to Cart</a>
                    </div>
                </li>
            </ul>
        {% endfor %}
    </section>
    </div>
-->

base/templates/base/filters.html
{% load static %}
<style>
    .no-bullets {
    list-style: none;
  }
  .no-bullets h3{
    font-size: 15px;
  }
</style>
<h3>Filters</h3>
<hr>
{% for cat in category %}
<ul class="no-bullets">
        {% if cat.product_set.all.count > 0 %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <a href="{% url 'base:search-product'%}?q={{cat.name}}"><h5>{{cat.name}}</h5></a>
            </a>
            <ul class="no-bullets dropdown-menu">
                {% for product in cat.product_set.all %}
                    
                        <li>
                            <div>
                            <a class="dropdown-item" href="{% url 'base:search-product'%}?q={{product.name}}" title="{{product.name}}">
                            <h3>{{product}}</h3>
                            </a>
                            </div>
                        </li>
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        </ul>
{% endfor %}


        <!--
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <li><a >Electronics</a></li>
              <li><a class="dropdown-item" href="#">Fashion</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Mobile</a></li>
              <li><a class="dropdown-item" href="#">Appliances</a></li>
            </ul>
          </li>
        -->

base/templates/base/home.html
{% extends 'main.html' %}
{% block content %}
<section class="banner">
    <h2>Welcome to My Store</h2>
    <p>Shop the latest trends in fashion and accessories.</p>
    <a href="#" class="btn">Shop Now</a>
</section>

{% include 'base/recent_section.html' %}
{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}
{% block content %}
<div>
    {% if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" placeholder="Enter username"/>
        <label>Password</label>
        <input type="password" name="password" placeholder="Enter Password"/>
        <input type="submit" value="Login"/>
    </form>
    <p>Haven't Signed up ?</p>
    <a href="{% url 'base:register' %}">Sign up</a>
</div>
{% else %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register"/>
    </form>
    <p>Alredy singed up yet ?</p>
    <a href="{% url 'base:login' %}">Sign In</a>
</div>
{% endif %}
</div>


{% endblock %}